[tool.black]
line-length = 120

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = """
  --cov=boedb --cov-report=html
"""

[tool.coverage.run]
source = ["boedb"]
omit = [
  "test*.py",
  "tests/__init__.py",
  "config.py",
]

[tool.coverage.report]
exclude_lines = [
  "pragma: no cover",
  "def __repr__",
  "def __str__",
  "raise NotImplementedError",
  "if __name__ == .__main__.:",
]

[tool.coverage.html]
directory = "htmlcov"
