[tool.pytest.ini_options]
addopts = """
  --cov
"""

[tool.coverage.run]
source = ["boedb"]

[tool.coverage.report]
exclude_lines = [
  "pragma: no cover",
  "def __repr__",
  "def __str__",
  "raise NotImplementedError",
  "if __name__ == .__main__.:",
]

[tool.black]
line-length = 120

[tool.isort]
profile = "black"