[tool.black]
line-length = 110

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = """
  --cov=boedb --cov-report=html \
  --ignore=boedb/tests/client_tools
"""

markers = [
  "integration: tests running whole systems with minimal mocking"
]


[tool.pylint.main]
disable = [
  "too-few-public-methods",
  "signature-differs",
  "unused-argument",
  "logging-fstring-interpolation",
  "missing-function-docstring",
  "missing-class-docstring",
  "missing-module-docstring",
]

[tool.pylint.format]
max-line-length = 110

[tool.coverage.run]
source = ["boedb"]
omit = [
  "test*.py",
  "tests/__init__.py",
  "config.py",
]

[tool.coverage.report]
exclude_lines = [
  "pragma: no cover",
  "def __repr__",
  "def __str__",
  "raise NotImplementedError",
  "logger", "logging",
  "if __name__ == .__main__.:",
]

[tool.coverage.html]
directory = "htmlcov"
